export const user_types = {
    ADD_USER: "ADD_USER",
    USER_ERROR: "USER_ERROR",
    USER_UPDATE_ERROR: "USER_UPDATE_ERROR",
    CHANGE_ADMIN: "CHANGE_ADMIN",
    CHANGE_HEADER: "CHANGE_HEADER",
    UPDATE_USER_MESSAGE: "UPDATE_USER_MESSAGE",
    LOG_OUT: "LOG_OUT",
}
export const feed_types = {
    FETCH_TAGS: "FETCH_TAGS",
    CHANGE_ACTIVE_TAB: "CHANGE_ACTIVE_TAB",
    FETCH_FEEDS: "FETCH_FEEDS",
    SELECTED_TAG: "SELECTED_TAG",
    START_LOADER: "START_LOADER",
    REDIRECT_TO: "REDIRECT_TO",
    API_ERROR: "API_ERROR",
    EDIT_FEEDS: "EDIT_FEEDS",
    SEARCH_FEEDS: "SEARCH_FEEDS",
    EDIT_ARTICLE:"EDIT_ARTICLE",
    EDITED_ARTICLE:"EDITED_ARTICLE",
}